language: node_js
addons:
  ssh_known_hosts: 123.207.14.113
  apt:
    packages:
    - sshpass
node_js:
- stable
sudo: false
script:
- npm run build
after_success:
- export SSHPASS=$pwd
- sshpass -e scp -P $port ./deploy_oauth.sh $host:/usr/local/source/distss/
- sshpass -e ssh -p $host 'cd /usr/local/source/distss && sh deploy_api.sh'
env:
  global:
  - secure: ozwGeqzKCGv7//YSBUio69lJx/Wp5PzXNz4RH1SEnVzTAjua1Y6CXAB9VqGxaof3tVDxIW1EAI3RNwu+g1KJwik4vxVFesxDlHXWqrusV5AkyFyk9RYfkXFSy/gN1zoHKiB/e8cm/Jy5JdQkxtEsrivPZUGMAsm2mRMXZGzu3HeyTf7fSqetH+jT/TfSq5ymCzdWlRriXbGlOx85hvWThL8meFRmqe91BzKyt9VApPRjgum1uj8JFYwBN35jU34fSVU66XOvXpLaej7eq801nTJv+X/1yOP8LsF7KPr+mmWgmkTqL9pBcGnsqO97xBjgiAw4QW+ICoutBzO3O65c2uUqL3BrF1p/hgk2N5do/5rwPhf93OKod8lrTWVqHpQkw/7LtlFSpyWgCpjBK9iAr+Cj/Wg/YlkebF2UuvvKu0jgMJ4iAcexHENAEUHxCsoAjn/dQqxeN1IxBIW0PlAkMxXtKdmLaXyRR/QDNlcexm03A0Kj05HuTOHZKC9C06Sc9mAucmt6k7k3KXc3ueIouCxonUgP5fOzUlmanr6PiVHq1lH+dCq7qZw3HswAhzRoDx1ZJn9tLvhAhGuxezDIUASXA//WKZ88gBuHFPTRs9CNdlibbC6Td6tM6t2VqYK9uMPnlMse+tPdjNbrD3Q6wKuMI6QLfnBtoo9KUDNJnX8=
  - secure: gvJ36O2fTiQyZtxzBLV6n5TOiWUfWm0JzbfrN04ZiFxjGf1exWQBOW/rIXws7bvlgbQs48XJijBdXblmA/qEU7o10BovWBJif4nNcrTCDmkrFOh3gajihCWfZywYSSUOgmPuJQspFO4m4fTa8KAGjyWbtvvCyd781pAxYsvkCGJMCvgpCs7H8nJdoSdD08bkYvUEC1FQYnQ4PUx/PM+lkOa72ID5bBMFoTkb29MPLLEL/gZniLgboMWxtkmIhmBP5T74dcqEl+Kws37J5WK/HkVJ/Vu4nHH71+ME8J1B8AGutxygkoMWkdHzIJ1HK+K1dlSNKBTvRuVsykbfNFTxNmBSao9NxDOs7E4mhRY4iIAaWcpsP1NoC0gfVT4MCJVwMkojKvd/fSIfaTJ8Jsh5VKa7NhXD8ScwM/7MJgIXSkzrFIpJaHNDzq8w5pViyQU52NafJpBybUf9D4UwuXj6uDEj7jNRTZ7jKzXBhHKeociqREzr2ngvdU2YNSo18Zu2wK1AqGbNyDAHN5yS0zHqzRbFuVXDJPBURLve8r/vS3y3NahICMuMK+/AGxSnSMY+dduZNG3JqK2sdbM//+tRWeC4zgA4aGI5v5b0Km9W9BYq8N6z3ekoiIQ/OOHuCMNcysEBL0WrXwvObzbESfQDcTh+puuoOL7a0fgCOY20Jqw=
  - secure: hP+G66wf9xPAj69K8JVjDYRdQAacthvrtqNOan/kXsRTg2kB6kEIFM2+chhzGczNupyFg2JJy3MG74zejrxRwT07zXc0IIsdyQPBarfKxHUdZR7V47LK3KBulkNR3CiJ73jGcQvtQMZf8NatvokkwVhs0YwJn3mtS/pi9o+HR5fK4e0h1Mbisql2gFU4gjGv1QDQBaz9CQm2F7J53uLFXmnTv0ePs3IltT+cZFhVdoQ2dzTj5ACR1A/Mc68q7a+kn6S1df01U1vK9qVuh10epcJBZXUpxjrezkYQudZzPIGINMjmzYUuUHfa7Tr8vELk2CFlvCJic52JpqwmSjMgHofjJKvHMlHFTdyfO9u5OQ9MkH8+y6KNStU7sccNcF5vNjoOwGt6amCJWoJeSpS+j8le0y6GmJG3/noPhB5tPQHstO063P9rY5gWwwJOp3Km+08UzCmfCvYWezI0yT6+DA4UsfTG6ldZUb4Zxl9VhqGPqFG2SQy56/cL3Vs4/xcCyZwsludOicfG2BLGTduJBRZa3ndUmKWLLvYhnMBscxGiv2MRxoANfbgh4nsKdqtd1JvkRweM6cxfHN8RE2jcsL0pmu3Rkvkv5zt6FJl9YV1b0kcX4YzXzGWGjk0KZaggt7DmtA+ZiiN8LIpauTW6F5CXTpIOj/0B0iuWWn2TSN4=
before_install:
- openssl aes-256-cbc -K $encrypted_b64c5cc1f43e_key -iv $encrypted_b64c5cc1f43e_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
